st.subheader("🧠 전문가 평가 요약")
st.markdown("- 교통: ⭐⭐⭐⭐☆")
st.markdown("- 실거주 만족도: ⭐⭐⭐⭐☆")
st.markdown("- 학군/인프라: ⭐⭐⭐☆☆")
st.markdown("- 투자 안정성: ⭐⭐⭐⭐☆")
st.markdown("- 브랜드/프리미엄: ⭐⭐⭐⭐☆")

st.subheader("📊 시각화 차트")
st.bar_chart(점수 딕셔너리)
st.radar_chart(동일 딕셔너리)
