OPENAI_API_KEY = "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"
FIREBASE_API_KEY = "AIzaSyAikbMVAU9xOZp9wGdBAPwIPrNRGj0fUq4"
FIREBASE_AUTH_DOMAIN = "apt-value-app.firebaseapp.com"
FIREBASE_PROJECT_ID = "apt-value-app"
GOOGLE_APPLICATION_CREDENTIALS = "./d3a30d7f564ecdb9e9bd6b4da7109aa05dfcc68f.json"